name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Make sure you have a requirements.txt file
        pip install allure-pytest playwright

    - name: Install Playwright browsers
      run: playwright install --with-deps

    - name: Create Trello credentials file
      run: |
        echo '${{ secrets.TRELLO_CREDS }}' > Trello_creds.json
      env:
        TRELLO_CREDS: ${{ secrets.TRELLO_CREDS }}

    - name: Run tests with Allure
      run: |
        pytest --alluredir=allure-results

    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build Allure Report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        force_orphan: true

    - name: Print Allure Report URL
      run: |
        echo "Allure Report is available at: ${{ steps.allure-report.outputs.report_url }}"